"""``originals.keno`` — the provably-fair Keno Original (spec §A.8).

Pick 1–10 numbers from a **1–40** grid; ``sampleWithoutReplacement(40, 10)`` draws
10 distinct numbers from the seeded stream; the payout multiplier is read from a
per-``(picks, risk)`` table indexed by the number of ``hits`` (picks ∩ drawn).

**Hit distribution is hypergeometric** (spec §A.8):

    P(hits = h | picks = k) = C(k, h) · C(40 - k, 10 - h) / C(40, 10)

Each ``(picks, risk)`` payout vector ``{pay_h}`` is **TUNED** so the analytic RTP
``Σ_h P(h) · pay_h = 1 - edge`` to within ±0.2% *after* rounding each multiplier to
two decimals — verified independently for all 30 cells by ``tests/test_keno_rtp.py``
(the in-repo proof). The tables are published DATA in ``GameConfig.params["tables"]``
(configurable, DB-authoritative at runtime); :data:`DEFAULT_TABLES` is the engine
seed/default, never a literal inside :meth:`Keno.play` (the table is config, not code).

**Tuning method** (reproducible, for the record — the numbers are guarded by the
analytic test, not regenerated at runtime). For each ``(picks k, risk)``:

* the first paying hit-count ``t = clamp(mode(k) + offset, 1, k)`` where
  ``mode(k) = floor((k+1)·11 / 42)`` is the hypergeometric mode, and ``offset`` is
  ``{LOW: 0, MEDIUM: 1, HIGH: 2}`` — higher risk pays only on rarer (higher) hits;
* a **geometric** shape ``pay_h ∝ g^(h - t)`` over the winning tail ``h ∈ [t, k]``
  with ratio ``g`` ``{LOW: 3.0, MEDIUM: 4.0, HIGH: 6.0}`` (the volatility knob) keeps
  payouts monotonically increasing in hits and the top prize realistic;
* the shape is scaled so ``Σ P(h)·pay_h = 1 - edge``, rounded to two decimals, then
  a few single-cent adjustments (largest-effect-first) drive the post-rounding RTP
  back onto target — the table is OPTIMIZED to hit target; outcomes are NEVER clamped
  and no tolerance is loosened.

Pure: stdlib only (``math.comb`` is used only by the test, not here); entropy enters
solely via the injected ``RngStream``; the table + ``edge`` are read from ``cfg``. The
same ``(server_seed, client_seed, nonce)`` + ``input`` always yields the same draw and
multiplier — server == verifier by construction.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from engine.sampling import sample_without_replacement
from engine.types import GameConfig, InvalidBetInput, Outcome, RngStream

# The 1–40 grid and the fixed 10-number draw (spec §A.8).
_GRID = tuple(range(1, 41))
_GRID_LO, _GRID_HI = 1, 40
_DRAW_COUNT = 10
_MAX_PICKS = 10

_RISKS = ("LOW", "MEDIUM", "HIGH")
_DEFAULT_RISK = "MEDIUM"

# Tuned payout tables: risk -> picks -> (pay_0, pay_1, …, pay_picks). Each tuple has
# ``picks + 1`` entries (one per possible hit count 0..picks). Σ_h P(h)·pay_h = 0.99
# (edge 1%) within ±0.2% post-rounding — proven for every cell in test_keno_rtp.py.
# Generated by the tuning method documented in the module docstring (edge = 0.01).
DEFAULT_TABLES: dict[str, dict[int, tuple[float, ...]]] = {
    "LOW": {
        1: (0.0, 3.96),
        2: (0.0, 1.78, 5.29),
        3: (0.0, 1.03, 3.1, 9.3),
        4: (0.0, 0.66, 1.97, 5.94, 17.78),
        5: (0.0, 0.44, 1.32, 3.95, 11.83, 35.57),
        6: (0.0, 0.3, 0.9, 2.71, 8.13, 24.37, 73.1),
        7: (0.0, 0.0, 0.67, 2.02, 6.06, 18.14, 54.4, 163.45),
        8: (0.0, 0.0, 0.46, 1.38, 4.13, 12.38, 37.15, 111.72, 335.01),
        9: (0.0, 0.0, 0.32, 0.96, 2.89, 8.68, 25.99, 78.02, 233.97, 702.15),
        10: (0.0, 0.0, 0.23, 0.68, 2.05, 6.14, 18.42, 55.34, 165.9, 497.98, 1492.29),
    },
    "MEDIUM": {
        1: (0.0, 3.96),
        2: (0.0, 1.61, 6.43),
        3: (0.0, 0.0, 5.34, 21.43),
        4: (0.0, 0.0, 2.42, 9.71, 38.8),
        5: (0.0, 0.0, 1.28, 5.13, 20.5, 81.89),
        6: (0.0, 0.0, 0.73, 2.94, 11.75, 46.9, 187.84),
        7: (0.0, 0.0, 0.0, 2.08, 8.3, 33.2, 132.87, 531.6),
        8: (0.0, 0.0, 0.0, 1.2, 4.82, 19.24, 76.92, 307.93, 1231.43),
        9: (0.0, 0.0, 0.0, 0.73, 2.92, 11.68, 46.74, 186.83, 747.7, 2989.62),
        10: (0.0, 0.0, 0.0, 0.46, 1.83, 7.32, 29.34, 117.29, 468.99, 1876.41, 7505.13),
    },
    "HIGH": {
        1: (0.0, 3.96),
        2: (0.0, 0.0, 17.16),
        3: (0.0, 0.0, 0.0, 81.51),
        4: (0.0, 0.0, 0.0, 18.62, 111.64),
        5: (0.0, 0.0, 0.0, 6.58, 39.41, 236.78),
        6: (0.0, 0.0, 0.0, 2.81, 16.85, 101.1, 606.67),
        7: (0.0, 0.0, 0.0, 0.0, 10.47, 62.81, 376.8, 2261.09),
        8: (0.0, 0.0, 0.0, 0.0, 4.75, 28.53, 171.17, 1026.66, 6159.59),
        9: (0.0, 0.0, 0.0, 0.0, 2.35, 14.11, 84.6, 507.81, 3046.55, 18278.91),
        10: (0.0, 0.0, 0.0, 0.0, 1.23, 7.41, 44.42, 266.5, 1598.69, 9591.69, 57551.55),
    },
}


def default_params() -> dict[str, Any]:
    """The engine seed/default ``GameConfig.params`` for keno — JSON-friendly.

    Shapes :data:`DEFAULT_TABLES` into ``{"tables": {risk: {str(picks): [pay_h]}}}``
    (string picks keys so it round-trips through JSON / the DB ``GameConfig`` row).
    DB ``GameConfig.params`` is authoritative at runtime; this is the seed value.
    """
    return {
        "tables": {
            risk: {str(picks): list(pays) for picks, pays in by_picks.items()}
            for risk, by_picks in DEFAULT_TABLES.items()
        }
    }


@dataclass(frozen=True)
class Keno:
    """Conforms to ``engine.types.InstantGame`` (spec §A.8)."""

    id: str = "originals.keno"

    def validate_input(self, input: dict[str, Any], cfg: GameConfig) -> None:
        """Reject malformed / out-of-band keno input BEFORE any money moves (pure).

        ``picks`` must be a list/tuple of 1–10 DISTINCT integers, each in [1, 40];
        ``risk`` (default ``MEDIUM``) must be one of LOW/MEDIUM/HIGH. This is the
        COMPLETE fence — passing it guarantees :meth:`play` cannot raise on this
        input (a valid ``(risk, |picks|)`` always resolves a table row).
        """
        if "picks" not in input:
            raise InvalidBetInput("keno requires 'picks'")
        picks = input["picks"]
        if not isinstance(picks, (list, tuple)):
            raise InvalidBetInput(f"keno 'picks' must be a list, got {type(picks).__name__}")
        if not (1 <= len(picks) <= _MAX_PICKS):
            raise InvalidBetInput(
                f"keno 'picks' must have 1..{_MAX_PICKS} numbers, got {len(picks)}"
            )
        for p in picks:
            # bool is a subclass of int — reject it explicitly so True/False can't
            # masquerade as 1/0.
            if not isinstance(p, int) or isinstance(p, bool):
                raise InvalidBetInput(f"keno 'picks' must be integers, got {p!r}")
            if not (_GRID_LO <= p <= _GRID_HI):
                raise InvalidBetInput(
                    f"keno pick {p} out of range [{_GRID_LO}, {_GRID_HI}]"
                )
        if len(set(picks)) != len(picks):
            raise InvalidBetInput(f"keno 'picks' must be distinct, got {list(picks)}")
        risk = str(input.get("risk", _DEFAULT_RISK)).upper()
        if risk not in _RISKS:
            raise InvalidBetInput(
                f"keno 'risk' must be one of {_RISKS}, got {risk!r}"
            )

    def play(self, input: dict[str, Any], rng: RngStream, cfg: GameConfig) -> Outcome:
        """Resolve one keno bet — pure function of (input, rng stream, cfg).

        Draws 10 distinct numbers from the 1–40 grid (consuming exactly 10 draws,
        regardless of ``|picks|``), counts ``hits = |picks ∩ drawn|``, and looks up
        the multiplier from the tuned ``cfg.params["tables"][risk][picks]`` vector.
        """
        picks = list(input["picks"])
        risk = str(input.get("risk", _DEFAULT_RISK)).upper()

        drawn = sample_without_replacement(rng, _GRID, _DRAW_COUNT)
        hits = len(set(picks) & set(drawn))

        table = cfg.params["tables"][risk][str(len(picks))]
        multiplier = float(table[hits])

        return Outcome(
            multiplier=multiplier,
            detail={
                "drawn": list(drawn),
                "hits": hits,
                "picks": picks,
                "risk": risk,
            },
        )


# The module-level singleton the registry resolves (see engine.games.__init__).
GAME = Keno()
