"""initial games-layer schema + seed configs

Revision ID: 68e2a4e66e5a
Revises:
Create Date: 2026-06-27 20:45:57.450710

"""

from __future__ import annotations

from collections.abc import Sequence
from decimal import Decimal

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "68e2a4e66e5a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_configs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("edge", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("paytable", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rtp", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("volatility", sa.String(length=16), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "version", name="uq_game_config_game_version"),
    )
    op.create_index(op.f("ix_game_configs_game_id"), "game_configs", ["game_id"], unique=False)
    op.create_table(
        "game_limits",
        sa.Column("game_id", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=16), nullable=False),
        sa.Column("min_bet", sa.BigInteger(), nullable=False),
        sa.Column("max_bet", sa.BigInteger(), nullable=False),
        sa.Column("max_win", sa.BigInteger(), nullable=False),
        sa.Column("max_multiplier", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.PrimaryKeyConstraint("game_id", "currency"),
    )
    op.create_table(
        "jackpots",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("game_id", sa.String(length=64), nullable=False),
        sa.Column("pool_minor", sa.BigInteger(), nullable=False),
        sa.Column("pop_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jackpots_game_id"), "jackpots", ["game_id"], unique=False)
    op.create_table(
        "poker_tables",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("stakes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("seats", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=True),
        sa.Column("hand_no", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "client_seeds",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=128), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "server_seeds",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("seed_hash", sa.String(length=64), nullable=False),
        sa.Column("seed_encrypted", sa.String(length=512), nullable=False),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_server_seeds_user_id"), "server_seeds", ["user_id"], unique=False)
    op.create_table(
        "wallets",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=16), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("balance_minor", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "currency", "mode", name="uq_wallet_user_currency_mode"),
    )
    op.create_index(op.f("ix_wallets_user_id"), "wallets", ["user_id"], unique=False)
    op.create_table(
        "game_rounds",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("game_id", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("server_seed_id", sa.String(length=64), nullable=True),
        sa.Column("nonce", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("outcome", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("config_version", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["server_seed_id"],
            ["server_seeds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_game_rounds_game_id"), "game_rounds", ["game_id"], unique=False)
    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("wallet_id", sa.String(length=64), nullable=False),
        sa.Column("txn_id", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("delta_minor", sa.BigInteger(), nullable=False),
        sa.Column("balance_after", sa.BigInteger(), nullable=False),
        sa.Column("ref", sa.String(length=128), nullable=True),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ledger_entries_ts"), "ledger_entries", ["ts"], unique=False)
    op.create_index(op.f("ix_ledger_entries_txn_id"), "ledger_entries", ["txn_id"], unique=False)
    op.create_index(
        op.f("ix_ledger_entries_wallet_id"), "ledger_entries", ["wallet_id"], unique=False
    )
    op.create_table(
        "nonce_counters",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("server_seed_id", sa.String(length=64), nullable=False),
        sa.Column("value", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["server_seed_id"],
            ["server_seeds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "server_seed_id"),
    )
    op.create_table(
        "bets",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("round_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("wallet_id", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=16), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("stake_minor", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("multiplier", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("payout_minor", sa.BigInteger(), nullable=True),
        sa.Column("idempotency_key_debit", sa.String(length=128), nullable=True),
        sa.Column("idempotency_key_credit", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["game_rounds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key_credit"),
        sa.UniqueConstraint("idempotency_key_debit"),
    )
    op.create_index(op.f("ix_bets_round_id"), "bets", ["round_id"], unique=False)
    op.create_index(op.f("ix_bets_user_id"), "bets", ["user_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("bet_id", sa.String(length=64), nullable=True),
        sa.Column("round_id", sa.String(length=64), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["bet_id"],
            ["bets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["game_rounds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_bet_id"), "audit_events", ["bet_id"], unique=False)
    op.create_index(op.f("ix_audit_events_round_id"), "audit_events", ["round_id"], unique=False)
    op.create_index(op.f("ix_audit_events_ts"), "audit_events", ["ts"], unique=False)
    # ### end Alembic commands ###

    # Data seed — runs in the same migration (downgrade drops the tables, which
    # removes these rows, so no separate seed-delete is needed).
    seed_configs()


def seed_configs() -> None:
    """Seed authoritative runtime tables from defaults.

    Seeds: the reserved SYSTEM (house) account + one house Wallet per currency
    (the counterparty of every double-entry movement, §2.2), plus an example
    GameConfig/GameLimit pair. The engine ``registry.py`` is the source of these
    defaults once it exists (S5); while it is empty, this module-local list is
    the explicit fallback. DB ``GameConfig``/``GameLimit`` are AUTHORITATIVE at
    runtime — each later game step adds/updates its own rows.
    """
    # Reserved house account (§2.2).
    users = sa.table("users", sa.column("id", sa.String))
    op.bulk_insert(users, [{"id": "SYSTEM"}])

    # One house Wallet per supported currency (play-money GOLD).
    currencies = ["GOLD"]
    wallets = sa.table(
        "wallets",
        sa.column("id", sa.String),
        sa.column("user_id", sa.String),
        sa.column("currency", sa.String),
        sa.column("mode", sa.String),
        sa.column("balance_minor", sa.BigInteger),
    )
    op.bulk_insert(
        wallets,
        [
            {
                "id": f"house-{cur}",
                "user_id": "SYSTEM",
                "currency": cur,
                "mode": "PLAY",
                "balance_minor": 0,
            }
            for cur in currencies
        ],
    )

    # Example GameConfig (versioned) + GameLimit, seeded from defaults.
    game_configs = sa.table(
        "game_configs",
        sa.column("game_id", sa.String),
        sa.column("version", sa.Integer),
        sa.column("edge", sa.Numeric),
        sa.column("rtp", sa.Numeric),
        sa.column("volatility", sa.String),
        sa.column("enabled", sa.Boolean),
    )
    op.bulk_insert(
        game_configs,
        [
            {
                "game_id": "originals.dice",
                "version": 1,
                "edge": Decimal("0.010000"),
                "rtp": Decimal("0.990000"),
                "volatility": "low",
                "enabled": True,
            }
        ],
    )

    game_limits = sa.table(
        "game_limits",
        sa.column("game_id", sa.String),
        sa.column("currency", sa.String),
        sa.column("min_bet", sa.BigInteger),
        sa.column("max_bet", sa.BigInteger),
        sa.column("max_win", sa.BigInteger),
        sa.column("max_multiplier", sa.Numeric),
    )
    op.bulk_insert(
        game_limits,
        [
            {
                "game_id": "originals.dice",
                "currency": "GOLD",
                "min_bet": 1,
                "max_bet": 100_000_000,
                "max_win": 1_000_000_000,
                "max_multiplier": Decimal("9900.00000000"),
            }
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_events_ts"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_round_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_bet_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_bets_user_id"), table_name="bets")
    op.drop_index(op.f("ix_bets_round_id"), table_name="bets")
    op.drop_table("bets")
    op.drop_table("nonce_counters")
    op.drop_index(op.f("ix_ledger_entries_wallet_id"), table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_txn_id"), table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_ts"), table_name="ledger_entries")
    op.drop_table("ledger_entries")
    op.drop_index(op.f("ix_game_rounds_game_id"), table_name="game_rounds")
    op.drop_table("game_rounds")
    op.drop_index(op.f("ix_wallets_user_id"), table_name="wallets")
    op.drop_table("wallets")
    op.drop_index(op.f("ix_server_seeds_user_id"), table_name="server_seeds")
    op.drop_table("server_seeds")
    op.drop_table("client_seeds")
    op.drop_table("users")
    op.drop_table("poker_tables")
    op.drop_index(op.f("ix_jackpots_game_id"), table_name="jackpots")
    op.drop_table("jackpots")
    op.drop_table("game_limits")
    op.drop_index(op.f("ix_game_configs_game_id"), table_name="game_configs")
    op.drop_table("game_configs")
    # ### end Alembic commands ###
