/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/guest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Guest */
        post: operations["post_guest_auth_guest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Refresh */
        post: operations["post_refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/originals.crash/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Crash State
         * @description The current shared Crash round + the caller's active bets (resume on reconnect).
         *
         *     Identity is the token's user — a caller sees ONLY its own bets. ``404`` if no
         *     Crash round has ever opened in this deployment.
         */
        get: operations["get_crash_state_games_originals_crash_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/bet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Bet */
        post: operations["post_bet_games__game_id__bet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/spin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Spin
         * @description Slots spin (spec §461 ``POST /games/slots.{machineId}/spin``).
         *
         *     A thin synonym for ``/bet``: a slot spin settles atomically through the SAME
         *     shared bet loop (single debit → engine outcome → single credit), so this adds NO
         *     per-game logic — it just exposes the spec's named slots endpoint. The response is
         *     the §2.2 bet object whose ``outcome`` carries the grid + line/feature wins.
         */
        post: operations["post_spin_games__game_id__spin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Action
         * @description Advance a stateful round (Mines reveal/cashout, HiLo guess/cashout). Returns the
         *     safe client-facing projection only — never hidden state. Identity is
         *     server-authoritative.
         */
        post: operations["post_action_games__game_id__action_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get State
         * @description The caller's most recent round for this game (resume after reconnect).
         *
         *     Identity is the token's user — a caller can only read its OWN round.
         */
        get: operations["get_state_games__game_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fairness/{bet_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Fairness */
        get: operations["get_fairness_fairness__bet_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessToken */
        AccessToken: {
            /** Accesstoken */
            accessToken: string;
            /**
             * Tokentype
             * @default bearer
             */
            tokenType: string;
        };
        /**
         * ActionRequest
         * @description The /action intent for a stateful round (Mines reveal/cashout, HiLo guess/cashout).
         *     Identity comes from the token, NEVER the body; the server decides the outcome from its
         *     held state. Per-game fields (``cell`` for Mines, ``side`` for HiLo) are optional —
         *     each game validates the ones it needs in its pure ``step`` (the router stays generic).
         */
        ActionRequest: {
            /** Roundid */
            roundId: string;
            /** Op */
            op: string;
            /** Cell */
            cell?: number | null;
            /** Side */
            side?: string | null;
        };
        /**
         * BetObject
         * @description The spec §2.2 bet object — the return value of the loop / the REST envelope.
         */
        BetObject: {
            /** Betid */
            betId: string;
            /** Gameid */
            gameId: string;
            /** Userid */
            userId: string;
            /** Walletid */
            walletId: string;
            /** Currency */
            currency: string;
            /** Mode */
            mode: string;
            /** Stakeminor */
            stakeMinor: number;
            /** Status */
            status: string;
            fairness: components["schemas"]["Fairness"];
            /** Input */
            input: {
                [key: string]: unknown;
            };
            /** Outcome */
            outcome: {
                [key: string]: unknown;
            };
            /** Createdat */
            createdAt?: string | null;
            /** Settledat */
            settledAt?: string | null;
            /** Idempotencykeys */
            idempotencyKeys: {
                [key: string]: string;
            };
        };
        /**
         * BetRequest
         * @description The /bet intent. The client sends ONLY intent + stake; never an outcome and
         *     never an identity — ``userId`` is intentionally absent (it comes from the token,
         *     so a client cannot even express acting as another user).
         */
        BetRequest: {
            /** Betid */
            betId: string;
            /** Stakeminor */
            stakeMinor: number;
            /**
             * Currency
             * @default GOLD
             */
            currency: string;
            /**
             * Mode
             * @default PLAY
             */
            mode: string;
            /** Input */
            input?: {
                [key: string]: unknown;
            };
        };
        /**
         * Fairness
         * @description The public commit-reveal triple shown with a bet (spec §2.2).
         */
        Fairness: {
            /** Serverseedhash */
            serverSeedHash: string;
            /** Clientseed */
            clientSeed: string;
            /** Nonce */
            nonce: number;
        };
        /**
         * FairnessDisclosure
         * @description The §2.10 fairness payload: seeds (+revealed), nonce, derivation, link.
         */
        FairnessDisclosure: {
            /** Betid */
            betId: string;
            /** Gameid */
            gameId: string;
            /** Serverseedhash */
            serverSeedHash: string;
            /** Serverseed */
            serverSeed: string | null;
            /** Revealed */
            revealed: boolean;
            /** Clientseed */
            clientSeed: string;
            /** Nonce */
            nonce: number;
            /** Derivation */
            derivation: string;
            /** Verifierurl */
            verifierUrl: string;
        };
        /** GuestSessionResponse */
        GuestSessionResponse: {
            /** Userid */
            userId: string;
            /** Walletid */
            walletId: string;
            /** Currency */
            currency: string;
            /** Mode */
            mode: string;
            tokens: components["schemas"]["TokenPair"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MeResponse */
        MeResponse: {
            /** Userid */
            userId: string;
            /** Walletid */
            walletId: string;
            /** Currency */
            currency: string;
            /** Mode */
            mode: string;
            /** Balanceminor */
            balanceMinor: number;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refreshtoken */
            refreshToken: string;
        };
        /** TokenPair */
        TokenPair: {
            /** Accesstoken */
            accessToken: string;
            /** Refreshtoken */
            refreshToken: string;
            /**
             * Tokentype
             * @default bearer
             */
            tokenType: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_guest_auth_guest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestSessionResponse"];
                };
            };
        };
    };
    post_refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    get_crash_state_games_originals_crash_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    post_bet_games__game_id__bet_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BetObject"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_spin_games__game_id__spin_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BetObject"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_action_games__game_id__action_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_games__game_id__state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fairness_fairness__bet_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FairnessDisclosure"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
